# Generated by Django 2.2 on 2019-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.TextField(choices=[('New', 'new'), ('In progress', 'in progress'), ('Done', 'done')], default='new', max_length=40, verbose_name='Status'),
        ),
    ]
